export { default as Home } from './Home'
export { default as Add } from './Add'
export { default as Links } from './Links'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Settings } from './Settings'
export { default as NotFound } from './NotFound'
